// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/messages.proto

package org.ogreg.cortex.transport;

public final class MulticastProtocol {
  private MulticastProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class Messages extends
      com.google.protobuf.GeneratedMessage {
    // Use Messages.newBuilder() to construct.
    private Messages() {
      initFields();
    }
    private Messages(boolean noInit) {}
    
    private static final Messages defaultInstance;
    public static Messages getDefaultInstance() {
      return defaultInstance;
    }
    
    public Messages getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.ogreg.cortex.transport.MulticastProtocol.internal_static_org_ogreg_cortex_transport_Messages_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.ogreg.cortex.transport.MulticastProtocol.internal_static_org_ogreg_cortex_transport_Messages_fieldAccessorTable;
    }
    
    public static final class Discover extends
        com.google.protobuf.GeneratedMessage {
      // Use Discover.newBuilder() to construct.
      private Discover() {
        initFields();
      }
      private Discover(boolean noInit) {}
      
      private static final Discover defaultInstance;
      public static Discover getDefaultInstance() {
        return defaultInstance;
      }
      
      public Discover getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.ogreg.cortex.transport.MulticastProtocol.internal_static_org_ogreg_cortex_transport_Messages_Discover_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.ogreg.cortex.transport.MulticastProtocol.internal_static_org_ogreg_cortex_transport_Messages_Discover_fieldAccessorTable;
      }
      
      // required string clazz = 1;
      public static final int CLAZZ_FIELD_NUMBER = 1;
      private boolean hasClazz;
      private java.lang.String clazz_ = "";
      public boolean hasClazz() { return hasClazz; }
      public java.lang.String getClazz() { return clazz_; }
      
      // optional string identifier = 2;
      public static final int IDENTIFIER_FIELD_NUMBER = 2;
      private boolean hasIdentifier;
      private java.lang.String identifier_ = "";
      public boolean hasIdentifier() { return hasIdentifier; }
      public java.lang.String getIdentifier() { return identifier_; }
      
      private void initFields() {
      }
      public final boolean isInitialized() {
        if (!hasClazz) return false;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (hasClazz()) {
          output.writeString(1, getClazz());
        }
        if (hasIdentifier()) {
          output.writeString(2, getIdentifier());
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (hasClazz()) {
          size += com.google.protobuf.CodedOutputStream
            .computeStringSize(1, getClazz());
        }
        if (hasIdentifier()) {
          size += com.google.protobuf.CodedOutputStream
            .computeStringSize(2, getIdentifier());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      public static org.ogreg.cortex.transport.MulticastProtocol.Messages.Discover parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static org.ogreg.cortex.transport.MulticastProtocol.Messages.Discover parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static org.ogreg.cortex.transport.MulticastProtocol.Messages.Discover parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static org.ogreg.cortex.transport.MulticastProtocol.Messages.Discover parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static org.ogreg.cortex.transport.MulticastProtocol.Messages.Discover parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static org.ogreg.cortex.transport.MulticastProtocol.Messages.Discover parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static org.ogreg.cortex.transport.MulticastProtocol.Messages.Discover parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static org.ogreg.cortex.transport.MulticastProtocol.Messages.Discover parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static org.ogreg.cortex.transport.MulticastProtocol.Messages.Discover parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static org.ogreg.cortex.transport.MulticastProtocol.Messages.Discover parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(org.ogreg.cortex.transport.MulticastProtocol.Messages.Discover prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> {
        private org.ogreg.cortex.transport.MulticastProtocol.Messages.Discover result;
        
        // Construct using org.ogreg.cortex.transport.MulticastProtocol.Messages.Discover.newBuilder()
        private Builder() {}
        
        private static Builder create() {
          Builder builder = new Builder();
          builder.result = new org.ogreg.cortex.transport.MulticastProtocol.Messages.Discover();
          return builder;
        }
        
        protected org.ogreg.cortex.transport.MulticastProtocol.Messages.Discover internalGetResult() {
          return result;
        }
        
        public Builder clear() {
          if (result == null) {
            throw new IllegalStateException(
              "Cannot call clear() after build().");
          }
          result = new org.ogreg.cortex.transport.MulticastProtocol.Messages.Discover();
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(result);
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return org.ogreg.cortex.transport.MulticastProtocol.Messages.Discover.getDescriptor();
        }
        
        public org.ogreg.cortex.transport.MulticastProtocol.Messages.Discover getDefaultInstanceForType() {
          return org.ogreg.cortex.transport.MulticastProtocol.Messages.Discover.getDefaultInstance();
        }
        
        public boolean isInitialized() {
          return result.isInitialized();
        }
        public org.ogreg.cortex.transport.MulticastProtocol.Messages.Discover build() {
          if (result != null && !isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return buildPartial();
        }
        
        private org.ogreg.cortex.transport.MulticastProtocol.Messages.Discover buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          if (!isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return buildPartial();
        }
        
        public org.ogreg.cortex.transport.MulticastProtocol.Messages.Discover buildPartial() {
          if (result == null) {
            throw new IllegalStateException(
              "build() has already been called on this Builder.");
          }
          org.ogreg.cortex.transport.MulticastProtocol.Messages.Discover returnMe = result;
          result = null;
          return returnMe;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof org.ogreg.cortex.transport.MulticastProtocol.Messages.Discover) {
            return mergeFrom((org.ogreg.cortex.transport.MulticastProtocol.Messages.Discover)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(org.ogreg.cortex.transport.MulticastProtocol.Messages.Discover other) {
          if (other == org.ogreg.cortex.transport.MulticastProtocol.Messages.Discover.getDefaultInstance()) return this;
          if (other.hasClazz()) {
            setClazz(other.getClazz());
          }
          if (other.hasIdentifier()) {
            setIdentifier(other.getIdentifier());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  return this;
                }
                break;
              }
              case 10: {
                setClazz(input.readString());
                break;
              }
              case 18: {
                setIdentifier(input.readString());
                break;
              }
            }
          }
        }
        
        
        // required string clazz = 1;
        public boolean hasClazz() {
          return result.hasClazz();
        }
        public java.lang.String getClazz() {
          return result.getClazz();
        }
        public Builder setClazz(java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  result.hasClazz = true;
          result.clazz_ = value;
          return this;
        }
        public Builder clearClazz() {
          result.hasClazz = false;
          result.clazz_ = getDefaultInstance().getClazz();
          return this;
        }
        
        // optional string identifier = 2;
        public boolean hasIdentifier() {
          return result.hasIdentifier();
        }
        public java.lang.String getIdentifier() {
          return result.getIdentifier();
        }
        public Builder setIdentifier(java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  result.hasIdentifier = true;
          result.identifier_ = value;
          return this;
        }
        public Builder clearIdentifier() {
          result.hasIdentifier = false;
          result.identifier_ = getDefaultInstance().getIdentifier();
          return this;
        }
        
        // @@protoc_insertion_point(builder_scope:org.ogreg.cortex.transport.Messages.Discover)
      }
      
      static {
        defaultInstance = new Discover(true);
        org.ogreg.cortex.transport.MulticastProtocol.internalForceInit();
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:org.ogreg.cortex.transport.Messages.Discover)
    }
    
    public static final class ServiceLoc extends
        com.google.protobuf.GeneratedMessage {
      // Use ServiceLoc.newBuilder() to construct.
      private ServiceLoc() {
        initFields();
      }
      private ServiceLoc(boolean noInit) {}
      
      private static final ServiceLoc defaultInstance;
      public static ServiceLoc getDefaultInstance() {
        return defaultInstance;
      }
      
      public ServiceLoc getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.ogreg.cortex.transport.MulticastProtocol.internal_static_org_ogreg_cortex_transport_Messages_ServiceLoc_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.ogreg.cortex.transport.MulticastProtocol.internal_static_org_ogreg_cortex_transport_Messages_ServiceLoc_fieldAccessorTable;
      }
      
      // required string clazz = 1;
      public static final int CLAZZ_FIELD_NUMBER = 1;
      private boolean hasClazz;
      private java.lang.String clazz_ = "";
      public boolean hasClazz() { return hasClazz; }
      public java.lang.String getClazz() { return clazz_; }
      
      // optional string identifier = 2;
      public static final int IDENTIFIER_FIELD_NUMBER = 2;
      private boolean hasIdentifier;
      private java.lang.String identifier_ = "";
      public boolean hasIdentifier() { return hasIdentifier; }
      public java.lang.String getIdentifier() { return identifier_; }
      
      private void initFields() {
      }
      public final boolean isInitialized() {
        if (!hasClazz) return false;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (hasClazz()) {
          output.writeString(1, getClazz());
        }
        if (hasIdentifier()) {
          output.writeString(2, getIdentifier());
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (hasClazz()) {
          size += com.google.protobuf.CodedOutputStream
            .computeStringSize(1, getClazz());
        }
        if (hasIdentifier()) {
          size += com.google.protobuf.CodedOutputStream
            .computeStringSize(2, getIdentifier());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      public static org.ogreg.cortex.transport.MulticastProtocol.Messages.ServiceLoc parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static org.ogreg.cortex.transport.MulticastProtocol.Messages.ServiceLoc parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static org.ogreg.cortex.transport.MulticastProtocol.Messages.ServiceLoc parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static org.ogreg.cortex.transport.MulticastProtocol.Messages.ServiceLoc parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static org.ogreg.cortex.transport.MulticastProtocol.Messages.ServiceLoc parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static org.ogreg.cortex.transport.MulticastProtocol.Messages.ServiceLoc parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static org.ogreg.cortex.transport.MulticastProtocol.Messages.ServiceLoc parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static org.ogreg.cortex.transport.MulticastProtocol.Messages.ServiceLoc parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static org.ogreg.cortex.transport.MulticastProtocol.Messages.ServiceLoc parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static org.ogreg.cortex.transport.MulticastProtocol.Messages.ServiceLoc parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(org.ogreg.cortex.transport.MulticastProtocol.Messages.ServiceLoc prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> {
        private org.ogreg.cortex.transport.MulticastProtocol.Messages.ServiceLoc result;
        
        // Construct using org.ogreg.cortex.transport.MulticastProtocol.Messages.ServiceLoc.newBuilder()
        private Builder() {}
        
        private static Builder create() {
          Builder builder = new Builder();
          builder.result = new org.ogreg.cortex.transport.MulticastProtocol.Messages.ServiceLoc();
          return builder;
        }
        
        protected org.ogreg.cortex.transport.MulticastProtocol.Messages.ServiceLoc internalGetResult() {
          return result;
        }
        
        public Builder clear() {
          if (result == null) {
            throw new IllegalStateException(
              "Cannot call clear() after build().");
          }
          result = new org.ogreg.cortex.transport.MulticastProtocol.Messages.ServiceLoc();
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(result);
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return org.ogreg.cortex.transport.MulticastProtocol.Messages.ServiceLoc.getDescriptor();
        }
        
        public org.ogreg.cortex.transport.MulticastProtocol.Messages.ServiceLoc getDefaultInstanceForType() {
          return org.ogreg.cortex.transport.MulticastProtocol.Messages.ServiceLoc.getDefaultInstance();
        }
        
        public boolean isInitialized() {
          return result.isInitialized();
        }
        public org.ogreg.cortex.transport.MulticastProtocol.Messages.ServiceLoc build() {
          if (result != null && !isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return buildPartial();
        }
        
        private org.ogreg.cortex.transport.MulticastProtocol.Messages.ServiceLoc buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          if (!isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return buildPartial();
        }
        
        public org.ogreg.cortex.transport.MulticastProtocol.Messages.ServiceLoc buildPartial() {
          if (result == null) {
            throw new IllegalStateException(
              "build() has already been called on this Builder.");
          }
          org.ogreg.cortex.transport.MulticastProtocol.Messages.ServiceLoc returnMe = result;
          result = null;
          return returnMe;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof org.ogreg.cortex.transport.MulticastProtocol.Messages.ServiceLoc) {
            return mergeFrom((org.ogreg.cortex.transport.MulticastProtocol.Messages.ServiceLoc)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(org.ogreg.cortex.transport.MulticastProtocol.Messages.ServiceLoc other) {
          if (other == org.ogreg.cortex.transport.MulticastProtocol.Messages.ServiceLoc.getDefaultInstance()) return this;
          if (other.hasClazz()) {
            setClazz(other.getClazz());
          }
          if (other.hasIdentifier()) {
            setIdentifier(other.getIdentifier());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  return this;
                }
                break;
              }
              case 10: {
                setClazz(input.readString());
                break;
              }
              case 18: {
                setIdentifier(input.readString());
                break;
              }
            }
          }
        }
        
        
        // required string clazz = 1;
        public boolean hasClazz() {
          return result.hasClazz();
        }
        public java.lang.String getClazz() {
          return result.getClazz();
        }
        public Builder setClazz(java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  result.hasClazz = true;
          result.clazz_ = value;
          return this;
        }
        public Builder clearClazz() {
          result.hasClazz = false;
          result.clazz_ = getDefaultInstance().getClazz();
          return this;
        }
        
        // optional string identifier = 2;
        public boolean hasIdentifier() {
          return result.hasIdentifier();
        }
        public java.lang.String getIdentifier() {
          return result.getIdentifier();
        }
        public Builder setIdentifier(java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  result.hasIdentifier = true;
          result.identifier_ = value;
          return this;
        }
        public Builder clearIdentifier() {
          result.hasIdentifier = false;
          result.identifier_ = getDefaultInstance().getIdentifier();
          return this;
        }
        
        // @@protoc_insertion_point(builder_scope:org.ogreg.cortex.transport.Messages.ServiceLoc)
      }
      
      static {
        defaultInstance = new ServiceLoc(true);
        org.ogreg.cortex.transport.MulticastProtocol.internalForceInit();
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:org.ogreg.cortex.transport.Messages.ServiceLoc)
    }
    
    // required string cortex = 1;
    public static final int CORTEX_FIELD_NUMBER = 1;
    private boolean hasCortex;
    private java.lang.String cortex_ = "";
    public boolean hasCortex() { return hasCortex; }
    public java.lang.String getCortex() { return cortex_; }
    
    // optional .org.ogreg.cortex.transport.Messages.Discover discover = 2;
    public static final int DISCOVER_FIELD_NUMBER = 2;
    private boolean hasDiscover;
    private org.ogreg.cortex.transport.MulticastProtocol.Messages.Discover discover_;
    public boolean hasDiscover() { return hasDiscover; }
    public org.ogreg.cortex.transport.MulticastProtocol.Messages.Discover getDiscover() { return discover_; }
    
    // optional .org.ogreg.cortex.transport.Messages.ServiceLoc service_location = 3;
    public static final int SERVICE_LOCATION_FIELD_NUMBER = 3;
    private boolean hasServiceLocation;
    private org.ogreg.cortex.transport.MulticastProtocol.Messages.ServiceLoc serviceLocation_;
    public boolean hasServiceLocation() { return hasServiceLocation; }
    public org.ogreg.cortex.transport.MulticastProtocol.Messages.ServiceLoc getServiceLocation() { return serviceLocation_; }
    
    private void initFields() {
      discover_ = org.ogreg.cortex.transport.MulticastProtocol.Messages.Discover.getDefaultInstance();
      serviceLocation_ = org.ogreg.cortex.transport.MulticastProtocol.Messages.ServiceLoc.getDefaultInstance();
    }
    public final boolean isInitialized() {
      if (!hasCortex) return false;
      if (hasDiscover()) {
        if (!getDiscover().isInitialized()) return false;
      }
      if (hasServiceLocation()) {
        if (!getServiceLocation().isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasCortex()) {
        output.writeString(1, getCortex());
      }
      if (hasDiscover()) {
        output.writeMessage(2, getDiscover());
      }
      if (hasServiceLocation()) {
        output.writeMessage(3, getServiceLocation());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasCortex()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getCortex());
      }
      if (hasDiscover()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getDiscover());
      }
      if (hasServiceLocation()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getServiceLocation());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static org.ogreg.cortex.transport.MulticastProtocol.Messages parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.ogreg.cortex.transport.MulticastProtocol.Messages parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.ogreg.cortex.transport.MulticastProtocol.Messages parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.ogreg.cortex.transport.MulticastProtocol.Messages parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.ogreg.cortex.transport.MulticastProtocol.Messages parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.ogreg.cortex.transport.MulticastProtocol.Messages parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.ogreg.cortex.transport.MulticastProtocol.Messages parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.ogreg.cortex.transport.MulticastProtocol.Messages parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.ogreg.cortex.transport.MulticastProtocol.Messages parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.ogreg.cortex.transport.MulticastProtocol.Messages parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.ogreg.cortex.transport.MulticastProtocol.Messages prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private org.ogreg.cortex.transport.MulticastProtocol.Messages result;
      
      // Construct using org.ogreg.cortex.transport.MulticastProtocol.Messages.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new org.ogreg.cortex.transport.MulticastProtocol.Messages();
        return builder;
      }
      
      protected org.ogreg.cortex.transport.MulticastProtocol.Messages internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new org.ogreg.cortex.transport.MulticastProtocol.Messages();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.ogreg.cortex.transport.MulticastProtocol.Messages.getDescriptor();
      }
      
      public org.ogreg.cortex.transport.MulticastProtocol.Messages getDefaultInstanceForType() {
        return org.ogreg.cortex.transport.MulticastProtocol.Messages.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public org.ogreg.cortex.transport.MulticastProtocol.Messages build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private org.ogreg.cortex.transport.MulticastProtocol.Messages buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public org.ogreg.cortex.transport.MulticastProtocol.Messages buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        org.ogreg.cortex.transport.MulticastProtocol.Messages returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.ogreg.cortex.transport.MulticastProtocol.Messages) {
          return mergeFrom((org.ogreg.cortex.transport.MulticastProtocol.Messages)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.ogreg.cortex.transport.MulticastProtocol.Messages other) {
        if (other == org.ogreg.cortex.transport.MulticastProtocol.Messages.getDefaultInstance()) return this;
        if (other.hasCortex()) {
          setCortex(other.getCortex());
        }
        if (other.hasDiscover()) {
          mergeDiscover(other.getDiscover());
        }
        if (other.hasServiceLocation()) {
          mergeServiceLocation(other.getServiceLocation());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setCortex(input.readString());
              break;
            }
            case 18: {
              org.ogreg.cortex.transport.MulticastProtocol.Messages.Discover.Builder subBuilder = org.ogreg.cortex.transport.MulticastProtocol.Messages.Discover.newBuilder();
              if (hasDiscover()) {
                subBuilder.mergeFrom(getDiscover());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setDiscover(subBuilder.buildPartial());
              break;
            }
            case 26: {
              org.ogreg.cortex.transport.MulticastProtocol.Messages.ServiceLoc.Builder subBuilder = org.ogreg.cortex.transport.MulticastProtocol.Messages.ServiceLoc.newBuilder();
              if (hasServiceLocation()) {
                subBuilder.mergeFrom(getServiceLocation());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setServiceLocation(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // required string cortex = 1;
      public boolean hasCortex() {
        return result.hasCortex();
      }
      public java.lang.String getCortex() {
        return result.getCortex();
      }
      public Builder setCortex(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasCortex = true;
        result.cortex_ = value;
        return this;
      }
      public Builder clearCortex() {
        result.hasCortex = false;
        result.cortex_ = getDefaultInstance().getCortex();
        return this;
      }
      
      // optional .org.ogreg.cortex.transport.Messages.Discover discover = 2;
      public boolean hasDiscover() {
        return result.hasDiscover();
      }
      public org.ogreg.cortex.transport.MulticastProtocol.Messages.Discover getDiscover() {
        return result.getDiscover();
      }
      public Builder setDiscover(org.ogreg.cortex.transport.MulticastProtocol.Messages.Discover value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasDiscover = true;
        result.discover_ = value;
        return this;
      }
      public Builder setDiscover(org.ogreg.cortex.transport.MulticastProtocol.Messages.Discover.Builder builderForValue) {
        result.hasDiscover = true;
        result.discover_ = builderForValue.build();
        return this;
      }
      public Builder mergeDiscover(org.ogreg.cortex.transport.MulticastProtocol.Messages.Discover value) {
        if (result.hasDiscover() &&
            result.discover_ != org.ogreg.cortex.transport.MulticastProtocol.Messages.Discover.getDefaultInstance()) {
          result.discover_ =
            org.ogreg.cortex.transport.MulticastProtocol.Messages.Discover.newBuilder(result.discover_).mergeFrom(value).buildPartial();
        } else {
          result.discover_ = value;
        }
        result.hasDiscover = true;
        return this;
      }
      public Builder clearDiscover() {
        result.hasDiscover = false;
        result.discover_ = org.ogreg.cortex.transport.MulticastProtocol.Messages.Discover.getDefaultInstance();
        return this;
      }
      
      // optional .org.ogreg.cortex.transport.Messages.ServiceLoc service_location = 3;
      public boolean hasServiceLocation() {
        return result.hasServiceLocation();
      }
      public org.ogreg.cortex.transport.MulticastProtocol.Messages.ServiceLoc getServiceLocation() {
        return result.getServiceLocation();
      }
      public Builder setServiceLocation(org.ogreg.cortex.transport.MulticastProtocol.Messages.ServiceLoc value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasServiceLocation = true;
        result.serviceLocation_ = value;
        return this;
      }
      public Builder setServiceLocation(org.ogreg.cortex.transport.MulticastProtocol.Messages.ServiceLoc.Builder builderForValue) {
        result.hasServiceLocation = true;
        result.serviceLocation_ = builderForValue.build();
        return this;
      }
      public Builder mergeServiceLocation(org.ogreg.cortex.transport.MulticastProtocol.Messages.ServiceLoc value) {
        if (result.hasServiceLocation() &&
            result.serviceLocation_ != org.ogreg.cortex.transport.MulticastProtocol.Messages.ServiceLoc.getDefaultInstance()) {
          result.serviceLocation_ =
            org.ogreg.cortex.transport.MulticastProtocol.Messages.ServiceLoc.newBuilder(result.serviceLocation_).mergeFrom(value).buildPartial();
        } else {
          result.serviceLocation_ = value;
        }
        result.hasServiceLocation = true;
        return this;
      }
      public Builder clearServiceLocation() {
        result.hasServiceLocation = false;
        result.serviceLocation_ = org.ogreg.cortex.transport.MulticastProtocol.Messages.ServiceLoc.getDefaultInstance();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:org.ogreg.cortex.transport.Messages)
    }
    
    static {
      defaultInstance = new Messages(true);
      org.ogreg.cortex.transport.MulticastProtocol.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.ogreg.cortex.transport.Messages)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_ogreg_cortex_transport_Messages_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_ogreg_cortex_transport_Messages_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_ogreg_cortex_transport_Messages_Discover_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_ogreg_cortex_transport_Messages_Discover_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_ogreg_cortex_transport_Messages_ServiceLoc_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_ogreg_cortex_transport_Messages_ServiceLoc_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035src/main/proto/messages.proto\022\032org.ogr" +
      "eg.cortex.transport\"\206\002\n\010Messages\022\016\n\006cort" +
      "ex\030\001 \002(\t\022?\n\010discover\030\002 \001(\0132-.org.ogreg.c" +
      "ortex.transport.Messages.Discover\022I\n\020ser" +
      "vice_location\030\003 \001(\0132/.org.ogreg.cortex.t" +
      "ransport.Messages.ServiceLoc\032-\n\010Discover" +
      "\022\r\n\005clazz\030\001 \002(\t\022\022\n\nidentifier\030\002 \001(\t\032/\n\nS" +
      "erviceLoc\022\r\n\005clazz\030\001 \002(\t\022\022\n\nidentifier\030\002" +
      " \001(\tB\023B\021MulticastProtocol"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_org_ogreg_cortex_transport_Messages_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_org_ogreg_cortex_transport_Messages_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_ogreg_cortex_transport_Messages_descriptor,
              new java.lang.String[] { "Cortex", "Discover", "ServiceLocation", },
              org.ogreg.cortex.transport.MulticastProtocol.Messages.class,
              org.ogreg.cortex.transport.MulticastProtocol.Messages.Builder.class);
          internal_static_org_ogreg_cortex_transport_Messages_Discover_descriptor =
            internal_static_org_ogreg_cortex_transport_Messages_descriptor.getNestedTypes().get(0);
          internal_static_org_ogreg_cortex_transport_Messages_Discover_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_ogreg_cortex_transport_Messages_Discover_descriptor,
              new java.lang.String[] { "Clazz", "Identifier", },
              org.ogreg.cortex.transport.MulticastProtocol.Messages.Discover.class,
              org.ogreg.cortex.transport.MulticastProtocol.Messages.Discover.Builder.class);
          internal_static_org_ogreg_cortex_transport_Messages_ServiceLoc_descriptor =
            internal_static_org_ogreg_cortex_transport_Messages_descriptor.getNestedTypes().get(1);
          internal_static_org_ogreg_cortex_transport_Messages_ServiceLoc_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_ogreg_cortex_transport_Messages_ServiceLoc_descriptor,
              new java.lang.String[] { "Clazz", "Identifier", },
              org.ogreg.cortex.transport.MulticastProtocol.Messages.ServiceLoc.class,
              org.ogreg.cortex.transport.MulticastProtocol.Messages.ServiceLoc.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
